apiVersion: v1
kind: Service
metadata:
  name: svc-customapp
  labels:
    product: customapp
spec:
  selector:
    app: app-customapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-customapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-customapp
    spec:
      containers:
      - image: pluralsightrm.azurecr.io/customapp:__Build.BuildId__
        imagePullPolicy: IfNotPresent
        name: customapp
        resources: {}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret